services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        # Use environment variables for TARGETARCH and GUNICORN_WORKERS, with defaults
        # Supported TARGETARCH values: amd64, arm64
        TARGETARCH: ${DOCKER_TARGETARCH:-amd64}
        GUNICORN_WORKERS: ${DOCKER_GUNICORN_WORKERS:-2}
    image: ov-website-clipper:${DOCKER_TARGETARCH:-amd64} # Tag image with architecture
    ports:
      - "5005:5001"
    volumes:
      - ./app/templates:/app/templates
      - ./uploads:/tmp/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - DISABLE_TRANSLATION=${DISABLE_TRANSLATION:-true}
      - RATE_LIMIT_PER_DAY=${RATE_LIMIT_PER_DAY:-200}
      - RATE_LIMIT_PER_HOUR=${RATE_LIMIT_PER_HOUR:-50}
      - RATE_LIMIT_CONVERT_PER_MINUTE=${RATE_LIMIT_CONVERT_PER_MINUTE:-10}
      - AD_CLIENT_ID=${AD_CLIENT_ID:-ca-pub-XXXXXXXXXXXXXXXX}  # Google AdSense Client ID
      - PAPAGO_CLIENT_ID=${PAPAGO_CLIENT_ID:-}
      - PAPAGO_CLIENT_SECRET=${PAPAGO_CLIENT_SECRET:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEEPL_API_KEY=${DEEPL_API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - npm_shared

networks:
  npm_shared:
    external: true