version: '3'

services:
  web:
    build: ./app
    ports:
      - "5005:5000"
    volumes:
      - ./app/templates:/app/templates
      - ./uploads:/tmp/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 