services:
  web:
    build: ./app
    ports:
      - "5005:5001"
    volumes:
      - ./app/templates:/app/templates
      - ./uploads:/tmp/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - DISABLE_TRANSLATION=true
      - RATE_LIMIT_PER_DAY=20 # 하루 요청 제한
      - RATE_LIMIT_PER_HOUR=5 # 시간당 요청 제한
      - RATE_LIMIT_CONVERT_PER_MINUTE=2 # 분당 변환 요청 제한
      - AD_CLIENT_ID_RIGHT=ca-pub-YOUR_RIGHT_AD_CLIENT_ID # 여기에 실제 오른쪽 광고 클라이언트 ID 입력
      - AD_SLOT_ID_RIGHT=YOUR_RIGHT_AD_SLOT_ID # 여기에 실제 오른쪽 광고 슬롯 ID 입력
      - AD_CLIENT_ID_BOTTOM=ca-pub-YOUR_BOTTOM_AD_CLIENT_ID # 여기에 실제 하단 광고 클라이언트 ID 입력
      - AD_SLOT_ID_BOTTOM=YOUR_BOTTOM_AD_SLOT_ID # 여기에 실제 하단 광고 슬롯 ID 입력
    restart: unless-stopped
